// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWCVd1IsEQAyGxZU4svQAj5EfT577IMDU',
    appId: '1:813289650706:web:45b0362ff51130a13036cb',
    messagingSenderId: '813289650706',
    projectId: 'nonsmoking-ef941',
    authDomain: 'nonsmoking-ef941.firebaseapp.com',
    storageBucket: 'nonsmoking-ef941.firebasestorage.app',
    measurementId: 'G-6R86C7FNB8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWLMMyXbswXWG19KBuZ3MQ_-feBdvHBOI',
    appId: '1:813289650706:android:6c1919718a717fdc3036cb',
    messagingSenderId: '813289650706',
    projectId: 'nonsmoking-ef941',
    storageBucket: 'nonsmoking-ef941.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCv3Ga7W3qcYavHEjJpfw4OD-Kx9V6NxMs',
    appId: '1:813289650706:ios:b3e218d04ea5ef573036cb',
    messagingSenderId: '813289650706',
    projectId: 'nonsmoking-ef941',
    storageBucket: 'nonsmoking-ef941.firebasestorage.app',
    iosBundleId: 'com.example.nonsmoking',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCv3Ga7W3qcYavHEjJpfw4OD-Kx9V6NxMs',
    appId: '1:813289650706:ios:b3e218d04ea5ef573036cb',
    messagingSenderId: '813289650706',
    projectId: 'nonsmoking-ef941',
    storageBucket: 'nonsmoking-ef941.firebasestorage.app',
    iosBundleId: 'com.example.nonsmoking',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAWCVd1IsEQAyGxZU4svQAj5EfT577IMDU',
    appId: '1:813289650706:web:9e39070caa7d704f3036cb',
    messagingSenderId: '813289650706',
    projectId: 'nonsmoking-ef941',
    authDomain: 'nonsmoking-ef941.firebaseapp.com',
    storageBucket: 'nonsmoking-ef941.firebasestorage.app',
    measurementId: 'G-67WEYB9HFQ',
  );
}
