// File generated by FlutterFire CLI (or restored from backup).
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
      case TargetPlatform.windows:
      case TargetPlatform.linux:
      case TargetPlatform.fuchsia:
        throw UnsupportedError(
          'DefaultFirebaseOptions are only set up for Android and iOS.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWLMMyXbswXWG19KBuZ3MQ_-feBdvHBOI',
    appId: '1:813289650706:android:6c1919718a717fdc3036cb',
    messagingSenderId: '813289650706',
    projectId: 'nonsmoking-ef941',
    storageBucket: 'nonsmoking-ef941.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWLMMyXbswXWG19KBuZ3MQ_-feBdvHBOI',
    appId: '1:813289650706:ios:b3e218d04ea5ef573036cb',
    messagingSenderId: '813289650706',
    projectId: 'nonsmoking-ef941',
    storageBucket: 'nonsmoking-ef941.firebasestorage.app',
  );
}
